pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "DocsApp-Suite"
include ':app'
include ':modules:text-editor'
include ':modules:spreadsheet'
include ':modules:presentation'
include ':modules:core'
include ':modules:fileformats'
include ':modules:pdf'
include ':modules:media'
include ':modules:converter'
include ':modules:transfer'
include ':modules:scanner'
include ':modules:pdftools'
include ':modules:library'
include ':modules:backup'
include ':modules:ocr'
include ':modules:recorder'
